services:
  qdrant:
    image: 'qdrant/qdrant:latest' #從 Docker Hub 下載 Qdrant
    ports:
      - "6333:6333" # 開放 Qdrant REST API　http://localhost:6333/dashboard#/collections
      - "6334:6334" # 開放 Qdrant gRPC API
      # "外部Port : 內部Port"
